/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class L101OutlineTreeProvider extends DefaultOutlineTreeProvider {
}
