/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mzattera.dsl.L101RuntimeModule;
import org.mzattera.dsl.L101StandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class L101IdeSetup extends L101StandaloneSetup {
  @Override
  public Injector createInjector() {
    L101RuntimeModule _l101RuntimeModule = new L101RuntimeModule();
    L101IdeModule _l101IdeModule = new L101IdeModule();
    return Guice.createInjector(Modules2.mixin(_l101RuntimeModule, _l101IdeModule));
  }
}
