/*
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.mzattera.dsl.l101.AdditiveOperator;
import org.mzattera.dsl.l101.AssignmentStatement;
import org.mzattera.dsl.l101.BreakStatement;
import org.mzattera.dsl.l101.Constant;
import org.mzattera.dsl.l101.ContinueStatement;
import org.mzattera.dsl.l101.Current;
import org.mzattera.dsl.l101.ForStatement;
import org.mzattera.dsl.l101.GotoStatement;
import org.mzattera.dsl.l101.IfStatement;
import org.mzattera.dsl.l101.Input;
import org.mzattera.dsl.l101.L101Package;
import org.mzattera.dsl.l101.Label;
import org.mzattera.dsl.l101.MultiplicativeOperator;
import org.mzattera.dsl.l101.NewLine;
import org.mzattera.dsl.l101.PrintStatement;
import org.mzattera.dsl.l101.Program;
import org.mzattera.dsl.l101.Statements;
import org.mzattera.dsl.l101.StoreStatement;
import org.mzattera.dsl.l101.UnaryOperator;
import org.mzattera.dsl.l101.UntilStatement;
import org.mzattera.dsl.l101.Variable;
import org.mzattera.dsl.l101.VariableAccess;
import org.mzattera.dsl.l101.VariableDeclaration;
import org.mzattera.dsl.l101.WhileStatement;
import org.mzattera.dsl.services.L101GrammarAccess;

@SuppressWarnings("all")
public class L101SemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private L101GrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == L101Package.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case L101Package.ADDITIVE_OPERATOR:
				sequence_AdditiveOperator(context, (AdditiveOperator) semanticObject); 
				return; 
			case L101Package.ASSIGNMENT_STATEMENT:
				sequence_AssignmentStatement(context, (AssignmentStatement) semanticObject); 
				return; 
			case L101Package.BREAK_STATEMENT:
				sequence_BreakStatement(context, (BreakStatement) semanticObject); 
				return; 
			case L101Package.CONSTANT:
				sequence_Constant(context, (Constant) semanticObject); 
				return; 
			case L101Package.CONTINUE_STATEMENT:
				sequence_ContinueStatement(context, (ContinueStatement) semanticObject); 
				return; 
			case L101Package.CURRENT:
				sequence_Current(context, (Current) semanticObject); 
				return; 
			case L101Package.FOR_STATEMENT:
				sequence_ForStatement(context, (ForStatement) semanticObject); 
				return; 
			case L101Package.GOTO_STATEMENT:
				sequence_GotoStatement(context, (GotoStatement) semanticObject); 
				return; 
			case L101Package.IF_STATEMENT:
				sequence_IfStatement(context, (IfStatement) semanticObject); 
				return; 
			case L101Package.INPUT:
				sequence_UserInput(context, (Input) semanticObject); 
				return; 
			case L101Package.LABEL:
				sequence_Label(context, (Label) semanticObject); 
				return; 
			case L101Package.MULTIPLICATIVE_OPERATOR:
				sequence_MultiplicativeOperator(context, (MultiplicativeOperator) semanticObject); 
				return; 
			case L101Package.NEW_LINE:
				sequence_NewLine(context, (NewLine) semanticObject); 
				return; 
			case L101Package.PRINT_STATEMENT:
				sequence_PrintStatement(context, (PrintStatement) semanticObject); 
				return; 
			case L101Package.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case L101Package.STATEMENTS:
				sequence_Statements(context, (Statements) semanticObject); 
				return; 
			case L101Package.STORE_STATEMENT:
				sequence_StoreStatement(context, (StoreStatement) semanticObject); 
				return; 
			case L101Package.UNARY_OPERATOR:
				sequence_UnaryOperator(context, (UnaryOperator) semanticObject); 
				return; 
			case L101Package.UNTIL_STATEMENT:
				sequence_UntilStatement(context, (UntilStatement) semanticObject); 
				return; 
			case L101Package.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			case L101Package.VARIABLE_ACCESS:
				sequence_VariableAccess(context, (VariableAccess) semanticObject); 
				return; 
			case L101Package.VARIABLE_DECLARATION:
				sequence_VariableDeclaration(context, (VariableDeclaration) semanticObject); 
				return; 
			case L101Package.WHILE_STATEMENT:
				sequence_WhileStatement(context, (WhileStatement) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns AdditiveOperator
	 *     AdditiveOperator returns AdditiveOperator
	 *     AdditiveOperator.AdditiveOperator_1_0 returns AdditiveOperator
	 *     MultiplicativeOperator returns AdditiveOperator
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns AdditiveOperator
	 *     UnaryOperator returns AdditiveOperator
	 *     Atomic returns AdditiveOperator
	 *
	 * Constraint:
	 *     (left=AdditiveOperator_AdditiveOperator_1_0 (op='+' | op='-') (right=VariableOrUserInput | right=Constant))
	 * </pre>
	 */
	protected void sequence_AdditiveOperator(ISerializationContext context, AdditiveOperator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     AssignmentStatement returns AssignmentStatement
	 *     Statement returns AssignmentStatement
	 *
	 * Constraint:
	 *     (
	 *         (op='=' operand=Expression) | 
	 *         ((op='+=' | op='-=' | op='/=' | op='*=' | op='%=') (operand=VariableOrUserInput | operand=Current | operand=Constant)) | 
	 *         (store=VariableAccess op='&lt;-&gt;' operand=Expression)
	 *     )
	 * </pre>
	 */
	protected void sequence_AssignmentStatement(ISerializationContext context, AssignmentStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns BreakStatement
	 *     SimpleControlStatement returns BreakStatement
	 *     BreakStatement returns BreakStatement
	 *
	 * Constraint:
	 *     code='BREAK'
	 * </pre>
	 */
	protected void sequence_BreakStatement(ISerializationContext context, BreakStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.SIMPLE_CONTROL_STATEMENT__CODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.SIMPLE_CONTROL_STATEMENT__CODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBreakStatementAccess().getCodeBREAKKeyword_1_0(), semanticObject.getCode());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns Constant
	 *     AdditiveOperator returns Constant
	 *     AdditiveOperator.AdditiveOperator_1_0 returns Constant
	 *     MultiplicativeOperator returns Constant
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns Constant
	 *     UnaryOperator returns Constant
	 *     Atomic returns Constant
	 *     Constant returns Constant
	 *     PrintParameter returns Constant
	 *
	 * Constraint:
	 *     (negative?='-'? value=NUMBER)
	 * </pre>
	 */
	protected void sequence_Constant(ISerializationContext context, Constant semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns ContinueStatement
	 *     SimpleControlStatement returns ContinueStatement
	 *     ContinueStatement returns ContinueStatement
	 *
	 * Constraint:
	 *     code='CONTINUE'
	 * </pre>
	 */
	protected void sequence_ContinueStatement(ISerializationContext context, ContinueStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.SIMPLE_CONTROL_STATEMENT__CODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.SIMPLE_CONTROL_STATEMENT__CODE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getContinueStatementAccess().getCodeCONTINUEKeyword_1_0(), semanticObject.getCode());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns Current
	 *     AdditiveOperator returns Current
	 *     AdditiveOperator.AdditiveOperator_1_0 returns Current
	 *     MultiplicativeOperator returns Current
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns Current
	 *     UnaryOperator returns Current
	 *     Atomic returns Current
	 *     Current returns Current
	 *     PrintParameter returns Current
	 *
	 * Constraint:
	 *     {Current}
	 * </pre>
	 */
	protected void sequence_Current(ISerializationContext context, Current semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns ForStatement
	 *     StructuredControlStatement returns ForStatement
	 *     LoopStatement returns ForStatement
	 *     ForStatement returns ForStatement
	 *
	 * Constraint:
	 *     (
	 *         (init=AssignmentStatement | init=SimpleStatement)? 
	 *         condition=AssignmentStatement 
	 *         (end=AssignmentStatement | end=SimpleStatement)? 
	 *         body=Statements
	 *     )
	 * </pre>
	 */
	protected void sequence_ForStatement(ISerializationContext context, ForStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns GotoStatement
	 *     SimpleStatement returns GotoStatement
	 *     GotoStatement returns GotoStatement
	 *
	 * Constraint:
	 *     label=[Label|ID]
	 * </pre>
	 */
	protected void sequence_GotoStatement(ISerializationContext context, GotoStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.GOTO_STATEMENT__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.GOTO_STATEMENT__LABEL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGotoStatementAccess().getLabelLabelIDTerminalRuleCall_1_0_1(), semanticObject.eGet(L101Package.Literals.GOTO_STATEMENT__LABEL, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns IfStatement
	 *     StructuredControlStatement returns IfStatement
	 *     IfStatement returns IfStatement
	 *
	 * Constraint:
	 *     (code='IF' condition=AssignmentStatement thenClause=Statements? elseClause=Statements?)
	 * </pre>
	 */
	protected void sequence_IfStatement(ISerializationContext context, IfStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns Label
	 *     Label returns Label
	 *
	 * Constraint:
	 *     (name=ID (target='V' | target='W' | target='Y' | target='Z')?)
	 * </pre>
	 */
	protected void sequence_Label(ISerializationContext context, Label semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns MultiplicativeOperator
	 *     AdditiveOperator returns MultiplicativeOperator
	 *     AdditiveOperator.AdditiveOperator_1_0 returns MultiplicativeOperator
	 *     MultiplicativeOperator returns MultiplicativeOperator
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns MultiplicativeOperator
	 *     UnaryOperator returns MultiplicativeOperator
	 *     Atomic returns MultiplicativeOperator
	 *
	 * Constraint:
	 *     (left=MultiplicativeOperator_MultiplicativeOperator_1_0 (op='*' | op='/' | op='%') (right=VariableOrUserInput | right=Constant))
	 * </pre>
	 */
	protected void sequence_MultiplicativeOperator(ISerializationContext context, MultiplicativeOperator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PrintParameter returns NewLine
	 *     NewLine returns NewLine
	 *
	 * Constraint:
	 *     {NewLine}
	 * </pre>
	 */
	protected void sequence_NewLine(ISerializationContext context, NewLine semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns PrintStatement
	 *     SimpleStatement returns PrintStatement
	 *     PrintStatement returns PrintStatement
	 *
	 * Constraint:
	 *     (params+=PrintParameter params+=PrintParameter*)?
	 * </pre>
	 */
	protected void sequence_PrintStatement(ISerializationContext context, PrintStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     (varDeclarations+=VariableDeclaration* body=Statements)
	 * </pre>
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statements returns Statements
	 *
	 * Constraint:
	 *     statements+=Statement*
	 * </pre>
	 */
	protected void sequence_Statements(ISerializationContext context, Statements semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns StoreStatement
	 *     SimpleStatement returns StoreStatement
	 *     StoreStatement returns StoreStatement
	 *
	 * Constraint:
	 *     ((param=Constant | param=UserInput) store=VariableAccess)
	 * </pre>
	 */
	protected void sequence_StoreStatement(ISerializationContext context, StoreStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Expression returns UnaryOperator
	 *     AdditiveOperator returns UnaryOperator
	 *     AdditiveOperator.AdditiveOperator_1_0 returns UnaryOperator
	 *     MultiplicativeOperator returns UnaryOperator
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns UnaryOperator
	 *     UnaryOperator returns UnaryOperator
	 *     Atomic returns UnaryOperator
	 *
	 * Constraint:
	 *     (
	 *         (
	 *             op='SQ' | 
	 *             op='SQRT' | 
	 *             op='INT' | 
	 *             op='DEC' | 
	 *             op='INV' | 
	 *             op='NEG' | 
	 *             op='ABS'
	 *         ) 
	 *         operand=UnaryOperator
	 *     )
	 * </pre>
	 */
	protected void sequence_UnaryOperator(ISerializationContext context, UnaryOperator semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns UntilStatement
	 *     StructuredControlStatement returns UntilStatement
	 *     LoopStatement returns UntilStatement
	 *     UntilStatement returns UntilStatement
	 *
	 * Constraint:
	 *     (condition=AssignmentStatement body=Statements)
	 * </pre>
	 */
	protected void sequence_UntilStatement(ISerializationContext context, UntilStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.STRUCTURED_CONTROL_STATEMENT__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.STRUCTURED_CONTROL_STATEMENT__CONDITION));
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.LOOP_STATEMENT__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.LOOP_STATEMENT__BODY));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUntilStatementAccess().getConditionAssignmentStatementParserRuleCall_1_0(), semanticObject.getCondition());
		feeder.accept(grammarAccess.getUntilStatementAccess().getBodyStatementsParserRuleCall_3_0(), semanticObject.getBody());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VariableOrUserInput returns Input
	 *     Expression returns Input
	 *     AdditiveOperator returns Input
	 *     AdditiveOperator.AdditiveOperator_1_0 returns Input
	 *     MultiplicativeOperator returns Input
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns Input
	 *     UnaryOperator returns Input
	 *     Atomic returns Input
	 *     UserInput returns Input
	 *
	 * Constraint:
	 *     {Input}
	 * </pre>
	 */
	protected void sequence_UserInput(ISerializationContext context, Input semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VariableAccess returns VariableAccess
	 *     VariableOrUserInput returns VariableAccess
	 *     Expression returns VariableAccess
	 *     AdditiveOperator returns VariableAccess
	 *     AdditiveOperator.AdditiveOperator_1_0 returns VariableAccess
	 *     MultiplicativeOperator returns VariableAccess
	 *     MultiplicativeOperator.MultiplicativeOperator_1_0 returns VariableAccess
	 *     UnaryOperator returns VariableAccess
	 *     Atomic returns VariableAccess
	 *     PrintParameter returns VariableAccess
	 *
	 * Constraint:
	 *     store=[Variable|ID]
	 * </pre>
	 */
	protected void sequence_VariableAccess(ISerializationContext context, VariableAccess semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.VARIABLE_ACCESS__STORE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.VARIABLE_ACCESS__STORE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableAccessAccess().getStoreVariableIDTerminalRuleCall_1_0_1(), semanticObject.eGet(L101Package.Literals.VARIABLE_ACCESS__STORE, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     VariableDeclaration returns VariableDeclaration
	 *
	 * Constraint:
	 *     (short?='SHORT'? vars+=Variable vars+=Variable*)
	 * </pre>
	 */
	protected void sequence_VariableDeclaration(ISerializationContext context, VariableDeclaration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Variable returns Variable
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         (
	 *             reg='B' | 
	 *             reg='B/' | 
	 *             reg='C' | 
	 *             reg='C/' | 
	 *             reg='D' | 
	 *             reg='D/' | 
	 *             reg='E' | 
	 *             reg='E/' | 
	 *             reg='F' | 
	 *             reg='F/'
	 *         )
	 *     )
	 * </pre>
	 */
	protected void sequence_Variable(ISerializationContext context, Variable semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Statement returns WhileStatement
	 *     StructuredControlStatement returns WhileStatement
	 *     LoopStatement returns WhileStatement
	 *     WhileStatement returns WhileStatement
	 *
	 * Constraint:
	 *     (body=Statements condition=AssignmentStatement)
	 * </pre>
	 */
	protected void sequence_WhileStatement(ISerializationContext context, WhileStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.LOOP_STATEMENT__BODY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.LOOP_STATEMENT__BODY));
			if (transientValues.isValueTransient(semanticObject, L101Package.Literals.STRUCTURED_CONTROL_STATEMENT__CONDITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, L101Package.Literals.STRUCTURED_CONTROL_STATEMENT__CONDITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWhileStatementAccess().getBodyStatementsParserRuleCall_1_0(), semanticObject.getBody());
		feeder.accept(grammarAccess.getWhileStatementAccess().getConditionAssignmentStatementParserRuleCall_3_0(), semanticObject.getCondition());
		feeder.finish();
	}
	
	
}
