/*
 * generated by Xtext 2.18.0
 */
package org.mzattera.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(L101InjectorProvider)
class L101ParsingTest {
	@Inject
//	ParseHelper<Program> parseHelper

	@Test
	def void loadModel() {
		// All tests implemented in several other classes.
	}
}
