/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101.impl;

import org.eclipse.emf.ecore.EClass;

import org.mzattera.dsl.l101.Current;
import org.mzattera.dsl.l101.L101Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Current</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CurrentImpl extends ExpressionImpl implements Current
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CurrentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return L101Package.Literals.CURRENT;
  }

} //CurrentImpl
