/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.mzattera.dsl.l101.IfStatement;
import org.mzattera.dsl.l101.L101Package;
import org.mzattera.dsl.l101.Statements;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.impl.IfStatementImpl#getCode <em>Code</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.impl.IfStatementImpl#getThenClause <em>Then Clause</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.impl.IfStatementImpl#getElseClause <em>Else Clause</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IfStatementImpl extends StructuredControlStatementImpl implements IfStatement
{
  /**
   * The default value of the '{@link #getCode() <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected static final String CODE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCode() <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCode()
   * @generated
   * @ordered
   */
  protected String code = CODE_EDEFAULT;

  /**
   * The cached value of the '{@link #getThenClause() <em>Then Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThenClause()
   * @generated
   * @ordered
   */
  protected Statements thenClause;

  /**
   * The cached value of the '{@link #getElseClause() <em>Else Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElseClause()
   * @generated
   * @ordered
   */
  protected Statements elseClause;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IfStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return L101Package.Literals.IF_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCode()
  {
    return code;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCode(String newCode)
  {
    String oldCode = code;
    code = newCode;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, L101Package.IF_STATEMENT__CODE, oldCode, code));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Statements getThenClause()
  {
    return thenClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetThenClause(Statements newThenClause, NotificationChain msgs)
  {
    Statements oldThenClause = thenClause;
    thenClause = newThenClause;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, L101Package.IF_STATEMENT__THEN_CLAUSE, oldThenClause, newThenClause);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThenClause(Statements newThenClause)
  {
    if (newThenClause != thenClause)
    {
      NotificationChain msgs = null;
      if (thenClause != null)
        msgs = ((InternalEObject)thenClause).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - L101Package.IF_STATEMENT__THEN_CLAUSE, null, msgs);
      if (newThenClause != null)
        msgs = ((InternalEObject)newThenClause).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - L101Package.IF_STATEMENT__THEN_CLAUSE, null, msgs);
      msgs = basicSetThenClause(newThenClause, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, L101Package.IF_STATEMENT__THEN_CLAUSE, newThenClause, newThenClause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Statements getElseClause()
  {
    return elseClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElseClause(Statements newElseClause, NotificationChain msgs)
  {
    Statements oldElseClause = elseClause;
    elseClause = newElseClause;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, L101Package.IF_STATEMENT__ELSE_CLAUSE, oldElseClause, newElseClause);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setElseClause(Statements newElseClause)
  {
    if (newElseClause != elseClause)
    {
      NotificationChain msgs = null;
      if (elseClause != null)
        msgs = ((InternalEObject)elseClause).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - L101Package.IF_STATEMENT__ELSE_CLAUSE, null, msgs);
      if (newElseClause != null)
        msgs = ((InternalEObject)newElseClause).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - L101Package.IF_STATEMENT__ELSE_CLAUSE, null, msgs);
      msgs = basicSetElseClause(newElseClause, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, L101Package.IF_STATEMENT__ELSE_CLAUSE, newElseClause, newElseClause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case L101Package.IF_STATEMENT__THEN_CLAUSE:
        return basicSetThenClause(null, msgs);
      case L101Package.IF_STATEMENT__ELSE_CLAUSE:
        return basicSetElseClause(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case L101Package.IF_STATEMENT__CODE:
        return getCode();
      case L101Package.IF_STATEMENT__THEN_CLAUSE:
        return getThenClause();
      case L101Package.IF_STATEMENT__ELSE_CLAUSE:
        return getElseClause();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case L101Package.IF_STATEMENT__CODE:
        setCode((String)newValue);
        return;
      case L101Package.IF_STATEMENT__THEN_CLAUSE:
        setThenClause((Statements)newValue);
        return;
      case L101Package.IF_STATEMENT__ELSE_CLAUSE:
        setElseClause((Statements)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case L101Package.IF_STATEMENT__CODE:
        setCode(CODE_EDEFAULT);
        return;
      case L101Package.IF_STATEMENT__THEN_CLAUSE:
        setThenClause((Statements)null);
        return;
      case L101Package.IF_STATEMENT__ELSE_CLAUSE:
        setElseClause((Statements)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case L101Package.IF_STATEMENT__CODE:
        return CODE_EDEFAULT == null ? code != null : !CODE_EDEFAULT.equals(code);
      case L101Package.IF_STATEMENT__THEN_CLAUSE:
        return thenClause != null;
      case L101Package.IF_STATEMENT__ELSE_CLAUSE:
        return elseClause != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (code: ");
    result.append(code);
    result.append(')');
    return result.toString();
  }

} //IfStatementImpl
