/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.mzattera.dsl.l101.L101Package;
import org.mzattera.dsl.l101.PrintParameter;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintParameterImpl extends MinimalEObjectImpl.Container implements PrintParameter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return L101Package.Literals.PRINT_PARAMETER;
  }

} //PrintParameterImpl
