/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101.impl;

import org.eclipse.emf.ecore.EClass;

import org.mzattera.dsl.l101.L101Package;
import org.mzattera.dsl.l101.UntilStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Until Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UntilStatementImpl extends LoopStatementImpl implements UntilStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UntilStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return L101Package.Literals.UNTIL_STATEMENT;
  }

} //UntilStatementImpl
