/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class L101DescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
