/*
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.mzattera.dsl.L101RuntimeModule
import org.mzattera.dsl.L101StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class L101IdeSetup extends L101StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new L101RuntimeModule, new L101IdeModule))
	}
	
}
