/*
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class L101UiModule extends AbstractL101UiModule {
}
