/*
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractL101ScopeProvider extends DelegatingScopeProvider {
}
