/*
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.mzattera.dsl.ide.contentassist.antlr.internal.InternalL101Parser;
import org.mzattera.dsl.services.L101GrammarAccess;

public class L101Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(L101GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, L101GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getVariableDeclarationAccess().getAlternatives_0(), "rule__VariableDeclaration__Alternatives_0");
			builder.put(grammarAccess.getVariableAccess().getRegAlternatives_2_0(), "rule__Variable__RegAlternatives_2_0");
			builder.put(grammarAccess.getVariableOrUserInputAccess().getAlternatives(), "rule__VariableOrUserInput__Alternatives");
			builder.put(grammarAccess.getAssignmentStatementAccess().getAlternatives(), "rule__AssignmentStatement__Alternatives");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOpAlternatives_1_0_0(), "rule__AssignmentStatement__OpAlternatives_1_0_0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOperandAlternatives_1_1_0(), "rule__AssignmentStatement__OperandAlternatives_1_1_0");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getOpAlternatives_1_1_0(), "rule__AdditiveOperator__OpAlternatives_1_1_0");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getRightAlternatives_1_2_0(), "rule__AdditiveOperator__RightAlternatives_1_2_0");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getOpAlternatives_1_1_0(), "rule__MultiplicativeOperator__OpAlternatives_1_1_0");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getRightAlternatives_1_2_0(), "rule__MultiplicativeOperator__RightAlternatives_1_2_0");
			builder.put(grammarAccess.getUnaryOperatorAccess().getAlternatives(), "rule__UnaryOperator__Alternatives");
			builder.put(grammarAccess.getUnaryOperatorAccess().getOpAlternatives_0_1_0(), "rule__UnaryOperator__OpAlternatives_0_1_0");
			builder.put(grammarAccess.getAtomicAccess().getAlternatives(), "rule__Atomic__Alternatives");
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getLabelAccess().getTargetAlternatives_1_1_0(), "rule__Label__TargetAlternatives_1_1_0");
			builder.put(grammarAccess.getSimpleStatementAccess().getAlternatives(), "rule__SimpleStatement__Alternatives");
			builder.put(grammarAccess.getSimpleControlStatementAccess().getAlternatives(), "rule__SimpleControlStatement__Alternatives");
			builder.put(grammarAccess.getStructuredControlStatementAccess().getAlternatives(), "rule__StructuredControlStatement__Alternatives");
			builder.put(grammarAccess.getLoopStatementAccess().getAlternatives(), "rule__LoopStatement__Alternatives");
			builder.put(grammarAccess.getStoreStatementAccess().getParamAlternatives_0_0(), "rule__StoreStatement__ParamAlternatives_0_0");
			builder.put(grammarAccess.getPrintParameterAccess().getAlternatives(), "rule__PrintParameter__Alternatives");
			builder.put(grammarAccess.getForStatementAccess().getInitAlternatives_1_0(), "rule__ForStatement__InitAlternatives_1_0");
			builder.put(grammarAccess.getForStatementAccess().getEndAlternatives_5_0(), "rule__ForStatement__EndAlternatives_5_0");
			builder.put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup_2(), "rule__VariableDeclaration__Group_2__0");
			builder.put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
			builder.put(grammarAccess.getVariableAccessAccess().getGroup(), "rule__VariableAccess__Group__0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getGroup_0(), "rule__AssignmentStatement__Group_0__0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getGroup_1(), "rule__AssignmentStatement__Group_1__0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getGroup_2(), "rule__AssignmentStatement__Group_2__0");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getGroup(), "rule__AdditiveOperator__Group__0");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getGroup_1(), "rule__AdditiveOperator__Group_1__0");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getGroup(), "rule__MultiplicativeOperator__Group__0");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getGroup_1(), "rule__MultiplicativeOperator__Group_1__0");
			builder.put(grammarAccess.getUnaryOperatorAccess().getGroup_0(), "rule__UnaryOperator__Group_0__0");
			builder.put(grammarAccess.getAtomicAccess().getGroup_4(), "rule__Atomic__Group_4__0");
			builder.put(grammarAccess.getCurrentAccess().getGroup(), "rule__Current__Group__0");
			builder.put(grammarAccess.getUserInputAccess().getGroup(), "rule__UserInput__Group__0");
			builder.put(grammarAccess.getConstantAccess().getGroup(), "rule__Constant__Group__0");
			builder.put(grammarAccess.getStatementsAccess().getGroup(), "rule__Statements__Group__0");
			builder.put(grammarAccess.getStatementAccess().getGroup_1(), "rule__Statement__Group_1__0");
			builder.put(grammarAccess.getStatementAccess().getGroup_2(), "rule__Statement__Group_2__0");
			builder.put(grammarAccess.getStatementAccess().getGroup_3(), "rule__Statement__Group_3__0");
			builder.put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
			builder.put(grammarAccess.getLabelAccess().getGroup_1(), "rule__Label__Group_1__0");
			builder.put(grammarAccess.getStoreStatementAccess().getGroup(), "rule__StoreStatement__Group__0");
			builder.put(grammarAccess.getPrintStatementAccess().getGroup(), "rule__PrintStatement__Group__0");
			builder.put(grammarAccess.getPrintStatementAccess().getGroup_2(), "rule__PrintStatement__Group_2__0");
			builder.put(grammarAccess.getPrintStatementAccess().getGroup_2_1(), "rule__PrintStatement__Group_2_1__0");
			builder.put(grammarAccess.getNewLineAccess().getGroup(), "rule__NewLine__Group__0");
			builder.put(grammarAccess.getGotoStatementAccess().getGroup(), "rule__GotoStatement__Group__0");
			builder.put(grammarAccess.getContinueStatementAccess().getGroup(), "rule__ContinueStatement__Group__0");
			builder.put(grammarAccess.getBreakStatementAccess().getGroup(), "rule__BreakStatement__Group__0");
			builder.put(grammarAccess.getIfStatementAccess().getGroup(), "rule__IfStatement__Group__0");
			builder.put(grammarAccess.getIfStatementAccess().getGroup_2(), "rule__IfStatement__Group_2__0");
			builder.put(grammarAccess.getIfStatementAccess().getGroup_3(), "rule__IfStatement__Group_3__0");
			builder.put(grammarAccess.getUntilStatementAccess().getGroup(), "rule__UntilStatement__Group__0");
			builder.put(grammarAccess.getForStatementAccess().getGroup(), "rule__ForStatement__Group__0");
			builder.put(grammarAccess.getWhileStatementAccess().getGroup(), "rule__WhileStatement__Group__0");
			builder.put(grammarAccess.getProgramAccess().getVarDeclarationsAssignment_0(), "rule__Program__VarDeclarationsAssignment_0");
			builder.put(grammarAccess.getProgramAccess().getBodyAssignment_1(), "rule__Program__BodyAssignment_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getShortAssignment_0_0(), "rule__VariableDeclaration__ShortAssignment_0_0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getVarsAssignment_1(), "rule__VariableDeclaration__VarsAssignment_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getVarsAssignment_2_1(), "rule__VariableDeclaration__VarsAssignment_2_1");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_0(), "rule__Variable__NameAssignment_0");
			builder.put(grammarAccess.getVariableAccess().getRegAssignment_2(), "rule__Variable__RegAssignment_2");
			builder.put(grammarAccess.getVariableAccessAccess().getStoreAssignment_1(), "rule__VariableAccess__StoreAssignment_1");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOpAssignment_0_0(), "rule__AssignmentStatement__OpAssignment_0_0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOperandAssignment_0_1(), "rule__AssignmentStatement__OperandAssignment_0_1");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOpAssignment_1_0(), "rule__AssignmentStatement__OpAssignment_1_0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOperandAssignment_1_1(), "rule__AssignmentStatement__OperandAssignment_1_1");
			builder.put(grammarAccess.getAssignmentStatementAccess().getStoreAssignment_2_0(), "rule__AssignmentStatement__StoreAssignment_2_0");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOpAssignment_2_1(), "rule__AssignmentStatement__OpAssignment_2_1");
			builder.put(grammarAccess.getAssignmentStatementAccess().getOperandAssignment_2_2(), "rule__AssignmentStatement__OperandAssignment_2_2");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getOpAssignment_1_1(), "rule__AdditiveOperator__OpAssignment_1_1");
			builder.put(grammarAccess.getAdditiveOperatorAccess().getRightAssignment_1_2(), "rule__AdditiveOperator__RightAssignment_1_2");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getOpAssignment_1_1(), "rule__MultiplicativeOperator__OpAssignment_1_1");
			builder.put(grammarAccess.getMultiplicativeOperatorAccess().getRightAssignment_1_2(), "rule__MultiplicativeOperator__RightAssignment_1_2");
			builder.put(grammarAccess.getUnaryOperatorAccess().getOpAssignment_0_1(), "rule__UnaryOperator__OpAssignment_0_1");
			builder.put(grammarAccess.getUnaryOperatorAccess().getOperandAssignment_0_2(), "rule__UnaryOperator__OperandAssignment_0_2");
			builder.put(grammarAccess.getConstantAccess().getNegativeAssignment_1(), "rule__Constant__NegativeAssignment_1");
			builder.put(grammarAccess.getConstantAccess().getValueAssignment_2(), "rule__Constant__ValueAssignment_2");
			builder.put(grammarAccess.getStatementsAccess().getStatementsAssignment_1(), "rule__Statements__StatementsAssignment_1");
			builder.put(grammarAccess.getLabelAccess().getNameAssignment_0(), "rule__Label__NameAssignment_0");
			builder.put(grammarAccess.getLabelAccess().getTargetAssignment_1_1(), "rule__Label__TargetAssignment_1_1");
			builder.put(grammarAccess.getStoreStatementAccess().getParamAssignment_0(), "rule__StoreStatement__ParamAssignment_0");
			builder.put(grammarAccess.getStoreStatementAccess().getStoreAssignment_2(), "rule__StoreStatement__StoreAssignment_2");
			builder.put(grammarAccess.getPrintStatementAccess().getParamsAssignment_2_0(), "rule__PrintStatement__ParamsAssignment_2_0");
			builder.put(grammarAccess.getPrintStatementAccess().getParamsAssignment_2_1_1(), "rule__PrintStatement__ParamsAssignment_2_1_1");
			builder.put(grammarAccess.getGotoStatementAccess().getLabelAssignment_1(), "rule__GotoStatement__LabelAssignment_1");
			builder.put(grammarAccess.getContinueStatementAccess().getCodeAssignment_1(), "rule__ContinueStatement__CodeAssignment_1");
			builder.put(grammarAccess.getBreakStatementAccess().getCodeAssignment_1(), "rule__BreakStatement__CodeAssignment_1");
			builder.put(grammarAccess.getIfStatementAccess().getCodeAssignment_0(), "rule__IfStatement__CodeAssignment_0");
			builder.put(grammarAccess.getIfStatementAccess().getConditionAssignment_1(), "rule__IfStatement__ConditionAssignment_1");
			builder.put(grammarAccess.getIfStatementAccess().getThenClauseAssignment_2_1(), "rule__IfStatement__ThenClauseAssignment_2_1");
			builder.put(grammarAccess.getIfStatementAccess().getElseClauseAssignment_3_1(), "rule__IfStatement__ElseClauseAssignment_3_1");
			builder.put(grammarAccess.getUntilStatementAccess().getConditionAssignment_1(), "rule__UntilStatement__ConditionAssignment_1");
			builder.put(grammarAccess.getUntilStatementAccess().getBodyAssignment_3(), "rule__UntilStatement__BodyAssignment_3");
			builder.put(grammarAccess.getForStatementAccess().getInitAssignment_1(), "rule__ForStatement__InitAssignment_1");
			builder.put(grammarAccess.getForStatementAccess().getConditionAssignment_3(), "rule__ForStatement__ConditionAssignment_3");
			builder.put(grammarAccess.getForStatementAccess().getEndAssignment_5(), "rule__ForStatement__EndAssignment_5");
			builder.put(grammarAccess.getForStatementAccess().getBodyAssignment_7(), "rule__ForStatement__BodyAssignment_7");
			builder.put(grammarAccess.getWhileStatementAccess().getBodyAssignment_1(), "rule__WhileStatement__BodyAssignment_1");
			builder.put(grammarAccess.getWhileStatementAccess().getConditionAssignment_3(), "rule__WhileStatement__ConditionAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private L101GrammarAccess grammarAccess;

	@Override
	protected InternalL101Parser createParser() {
		InternalL101Parser result = new InternalL101Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public L101GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(L101GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
