/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assignment Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.AssignmentStatement#getOp <em>Op</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.AssignmentStatement#getOperand <em>Operand</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.AssignmentStatement#getStore <em>Store</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getAssignmentStatement()
 * @model
 * @generated
 */
public interface AssignmentStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.mzattera.dsl.l101.L101Package#getAssignmentStatement_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.AssignmentStatement#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operand</em>' containment reference.
   * @see #setOperand(Expression)
   * @see org.mzattera.dsl.l101.L101Package#getAssignmentStatement_Operand()
   * @model containment="true"
   * @generated
   */
  Expression getOperand();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.AssignmentStatement#getOperand <em>Operand</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operand</em>' containment reference.
   * @see #getOperand()
   * @generated
   */
  void setOperand(Expression value);

  /**
   * Returns the value of the '<em><b>Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Store</em>' containment reference.
   * @see #setStore(Expression)
   * @see org.mzattera.dsl.l101.L101Package#getAssignmentStatement_Store()
   * @model containment="true"
   * @generated
   */
  Expression getStore();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.AssignmentStatement#getStore <em>Store</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Store</em>' containment reference.
   * @see #getStore()
   * @generated
   */
  void setStore(Expression value);

} // AssignmentStatement
