/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goto Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.GotoStatement#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getGotoStatement()
 * @model
 * @generated
 */
public interface GotoStatement extends SimpleStatement
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' reference.
   * @see #setLabel(Label)
   * @see org.mzattera.dsl.l101.L101Package#getGotoStatement_Label()
   * @model
   * @generated
   */
  Label getLabel();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.GotoStatement#getLabel <em>Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' reference.
   * @see #getLabel()
   * @generated
   */
  void setLabel(Label value);

} // GotoStatement
