/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.IfStatement#getCode <em>Code</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.IfStatement#getThenClause <em>Then Clause</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.IfStatement#getElseClause <em>Else Clause</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends StructuredControlStatement
{
  /**
   * Returns the value of the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code</em>' attribute.
   * @see #setCode(String)
   * @see org.mzattera.dsl.l101.L101Package#getIfStatement_Code()
   * @model
   * @generated
   */
  String getCode();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.IfStatement#getCode <em>Code</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code</em>' attribute.
   * @see #getCode()
   * @generated
   */
  void setCode(String value);

  /**
   * Returns the value of the '<em><b>Then Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Clause</em>' containment reference.
   * @see #setThenClause(Statements)
   * @see org.mzattera.dsl.l101.L101Package#getIfStatement_ThenClause()
   * @model containment="true"
   * @generated
   */
  Statements getThenClause();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.IfStatement#getThenClause <em>Then Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Clause</em>' containment reference.
   * @see #getThenClause()
   * @generated
   */
  void setThenClause(Statements value);

  /**
   * Returns the value of the '<em><b>Else Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Clause</em>' containment reference.
   * @see #setElseClause(Statements)
   * @see org.mzattera.dsl.l101.L101Package#getIfStatement_ElseClause()
   * @model containment="true"
   * @generated
   */
  Statements getElseClause();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.IfStatement#getElseClause <em>Else Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Else Clause</em>' containment reference.
   * @see #getElseClause()
   * @generated
   */
  void setElseClause(Statements value);

} // IfStatement
