/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mzattera.dsl.l101.L101Package#getInput()
 * @model
 * @generated
 */
public interface Input extends Expression
{
} // Input
