/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.mzattera.dsl.l101.L101Factory
 * @model kind="package"
 * @generated
 */
public interface L101Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "l101";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.github.io/mzattera/L101";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "l101";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  L101Package eINSTANCE = org.mzattera.dsl.l101.impl.L101PackageImpl.init();

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.ProgramImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Var Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__VAR_DECLARATIONS = 0;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__BODY = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.VariableDeclarationImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Short</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__SHORT = 0;

  /**
   * The feature id for the '<em><b>Vars</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VARS = 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.VariableImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The feature id for the '<em><b>Reg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__REG = 1;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.PrintParameterImpl <em>Print Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.PrintParameterImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getPrintParameter()
   * @generated
   */
  int PRINT_PARAMETER = 14;

  /**
   * The number of structural features of the '<em>Print Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_PARAMETER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.ExpressionImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 3;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = PRINT_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.StatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 6;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.AssignmentStatementImpl <em>Assignment Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.AssignmentStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getAssignmentStatement()
   * @generated
   */
  int ASSIGNMENT_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_STATEMENT__OP = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_STATEMENT__OPERAND = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_STATEMENT__STORE = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Assignment Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGNMENT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.StatementsImpl <em>Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.StatementsImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStatements()
   * @generated
   */
  int STATEMENTS = 5;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.LabelImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getLabel()
   * @generated
   */
  int LABEL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__TARGET = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.SimpleStatementImpl <em>Simple Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.SimpleStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getSimpleStatement()
   * @generated
   */
  int SIMPLE_STATEMENT = 8;

  /**
   * The number of structural features of the '<em>Simple Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.SimpleControlStatementImpl <em>Simple Control Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.SimpleControlStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getSimpleControlStatement()
   * @generated
   */
  int SIMPLE_CONTROL_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CONTROL_STATEMENT__CODE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Simple Control Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_CONTROL_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.StructuredControlStatementImpl <em>Structured Control Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.StructuredControlStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStructuredControlStatement()
   * @generated
   */
  int STRUCTURED_CONTROL_STATEMENT = 10;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCTURED_CONTROL_STATEMENT__CONDITION = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Structured Control Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.LoopStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getLoopStatement()
   * @generated
   */
  int LOOP_STATEMENT = 11;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__CONDITION = STRUCTURED_CONTROL_STATEMENT__CONDITION;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__BODY = STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Loop Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT_FEATURE_COUNT = STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.StoreStatementImpl <em>Store Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.StoreStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStoreStatement()
   * @generated
   */
  int STORE_STATEMENT = 12;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_STATEMENT__PARAM = SIMPLE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_STATEMENT__STORE = SIMPLE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Store Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STORE_STATEMENT_FEATURE_COUNT = SIMPLE_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.PrintStatementImpl <em>Print Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.PrintStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getPrintStatement()
   * @generated
   */
  int PRINT_STATEMENT = 13;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_STATEMENT__PARAMS = SIMPLE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_STATEMENT_FEATURE_COUNT = SIMPLE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.NewLineImpl <em>New Line</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.NewLineImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getNewLine()
   * @generated
   */
  int NEW_LINE = 15;

  /**
   * The number of structural features of the '<em>New Line</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEW_LINE_FEATURE_COUNT = PRINT_PARAMETER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.GotoStatementImpl <em>Goto Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.GotoStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getGotoStatement()
   * @generated
   */
  int GOTO_STATEMENT = 16;

  /**
   * The feature id for the '<em><b>Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_STATEMENT__LABEL = SIMPLE_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Goto Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_STATEMENT_FEATURE_COUNT = SIMPLE_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.ContinueStatementImpl <em>Continue Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.ContinueStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getContinueStatement()
   * @generated
   */
  int CONTINUE_STATEMENT = 17;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTINUE_STATEMENT__CODE = SIMPLE_CONTROL_STATEMENT__CODE;

  /**
   * The number of structural features of the '<em>Continue Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTINUE_STATEMENT_FEATURE_COUNT = SIMPLE_CONTROL_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.BreakStatementImpl <em>Break Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.BreakStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getBreakStatement()
   * @generated
   */
  int BREAK_STATEMENT = 18;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREAK_STATEMENT__CODE = SIMPLE_CONTROL_STATEMENT__CODE;

  /**
   * The number of structural features of the '<em>Break Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREAK_STATEMENT_FEATURE_COUNT = SIMPLE_CONTROL_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.IfStatementImpl <em>If Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.IfStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getIfStatement()
   * @generated
   */
  int IF_STATEMENT = 19;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__CONDITION = STRUCTURED_CONTROL_STATEMENT__CONDITION;

  /**
   * The feature id for the '<em><b>Code</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__CODE = STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Then Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__THEN_CLAUSE = STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Else Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT__ELSE_CLAUSE = STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_STATEMENT_FEATURE_COUNT = STRUCTURED_CONTROL_STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.UntilStatementImpl <em>Until Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.UntilStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getUntilStatement()
   * @generated
   */
  int UNTIL_STATEMENT = 20;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNTIL_STATEMENT__CONDITION = LOOP_STATEMENT__CONDITION;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNTIL_STATEMENT__BODY = LOOP_STATEMENT__BODY;

  /**
   * The number of structural features of the '<em>Until Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNTIL_STATEMENT_FEATURE_COUNT = LOOP_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.ForStatementImpl <em>For Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.ForStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getForStatement()
   * @generated
   */
  int FOR_STATEMENT = 21;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STATEMENT__CONDITION = LOOP_STATEMENT__CONDITION;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STATEMENT__BODY = LOOP_STATEMENT__BODY;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STATEMENT__INIT = LOOP_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STATEMENT__END = LOOP_STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>For Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_STATEMENT_FEATURE_COUNT = LOOP_STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.WhileStatementImpl <em>While Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.WhileStatementImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getWhileStatement()
   * @generated
   */
  int WHILE_STATEMENT = 22;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STATEMENT__CONDITION = LOOP_STATEMENT__CONDITION;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STATEMENT__BODY = LOOP_STATEMENT__BODY;

  /**
   * The number of structural features of the '<em>While Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_STATEMENT_FEATURE_COUNT = LOOP_STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.VariableAccessImpl <em>Variable Access</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.VariableAccessImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getVariableAccess()
   * @generated
   */
  int VARIABLE_ACCESS = 23;

  /**
   * The feature id for the '<em><b>Store</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ACCESS__STORE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Access</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_ACCESS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.AdditiveOperatorImpl <em>Additive Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.AdditiveOperatorImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getAdditiveOperator()
   * @generated
   */
  int ADDITIVE_OPERATOR = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_OPERATOR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_OPERATOR__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_OPERATOR__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Additive Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_OPERATOR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.MultiplicativeOperatorImpl <em>Multiplicative Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.MultiplicativeOperatorImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getMultiplicativeOperator()
   * @generated
   */
  int MULTIPLICATIVE_OPERATOR = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_OPERATOR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_OPERATOR__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_OPERATOR__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplicative Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_OPERATOR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.UnaryOperatorImpl <em>Unary Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.UnaryOperatorImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getUnaryOperator()
   * @generated
   */
  int UNARY_OPERATOR = 26;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_OPERATOR__OP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operand</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_OPERATOR__OPERAND = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Unary Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_OPERATOR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.CurrentImpl <em>Current</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.CurrentImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getCurrent()
   * @generated
   */
  int CURRENT = 27;

  /**
   * The number of structural features of the '<em>Current</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CURRENT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.InputImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getInput()
   * @generated
   */
  int INPUT = 28;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.mzattera.dsl.l101.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.mzattera.dsl.l101.impl.ConstantImpl
   * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 29;

  /**
   * The feature id for the '<em><b>Negative</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__NEGATIVE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__VALUE = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.mzattera.dsl.l101.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.mzattera.dsl.l101.Program#getVarDeclarations <em>Var Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Var Declarations</em>'.
   * @see org.mzattera.dsl.l101.Program#getVarDeclarations()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_VarDeclarations();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.Program#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.mzattera.dsl.l101.Program#getBody()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Body();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see org.mzattera.dsl.l101.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.VariableDeclaration#isShort <em>Short</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Short</em>'.
   * @see org.mzattera.dsl.l101.VariableDeclaration#isShort()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Short();

  /**
   * Returns the meta object for the containment reference list '{@link org.mzattera.dsl.l101.VariableDeclaration#getVars <em>Vars</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars</em>'.
   * @see org.mzattera.dsl.l101.VariableDeclaration#getVars()
   * @see #getVariableDeclaration()
   * @generated
   */
  EReference getVariableDeclaration_Vars();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.mzattera.dsl.l101.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mzattera.dsl.l101.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.Variable#getReg <em>Reg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Reg</em>'.
   * @see org.mzattera.dsl.l101.Variable#getReg()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Reg();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.mzattera.dsl.l101.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.AssignmentStatement <em>Assignment Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assignment Statement</em>'.
   * @see org.mzattera.dsl.l101.AssignmentStatement
   * @generated
   */
  EClass getAssignmentStatement();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.AssignmentStatement#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.mzattera.dsl.l101.AssignmentStatement#getOp()
   * @see #getAssignmentStatement()
   * @generated
   */
  EAttribute getAssignmentStatement_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.AssignmentStatement#getOperand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operand</em>'.
   * @see org.mzattera.dsl.l101.AssignmentStatement#getOperand()
   * @see #getAssignmentStatement()
   * @generated
   */
  EReference getAssignmentStatement_Operand();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.AssignmentStatement#getStore <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Store</em>'.
   * @see org.mzattera.dsl.l101.AssignmentStatement#getStore()
   * @see #getAssignmentStatement()
   * @generated
   */
  EReference getAssignmentStatement_Store();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Statements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statements</em>'.
   * @see org.mzattera.dsl.l101.Statements
   * @generated
   */
  EClass getStatements();

  /**
   * Returns the meta object for the containment reference list '{@link org.mzattera.dsl.l101.Statements#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.mzattera.dsl.l101.Statements#getStatements()
   * @see #getStatements()
   * @generated
   */
  EReference getStatements_Statements();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.mzattera.dsl.l101.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see org.mzattera.dsl.l101.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.Label#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.mzattera.dsl.l101.Label#getName()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Name();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.Label#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see org.mzattera.dsl.l101.Label#getTarget()
   * @see #getLabel()
   * @generated
   */
  EAttribute getLabel_Target();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.SimpleStatement <em>Simple Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Statement</em>'.
   * @see org.mzattera.dsl.l101.SimpleStatement
   * @generated
   */
  EClass getSimpleStatement();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.SimpleControlStatement <em>Simple Control Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Control Statement</em>'.
   * @see org.mzattera.dsl.l101.SimpleControlStatement
   * @generated
   */
  EClass getSimpleControlStatement();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.SimpleControlStatement#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see org.mzattera.dsl.l101.SimpleControlStatement#getCode()
   * @see #getSimpleControlStatement()
   * @generated
   */
  EAttribute getSimpleControlStatement_Code();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.StructuredControlStatement <em>Structured Control Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Structured Control Statement</em>'.
   * @see org.mzattera.dsl.l101.StructuredControlStatement
   * @generated
   */
  EClass getStructuredControlStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.StructuredControlStatement#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see org.mzattera.dsl.l101.StructuredControlStatement#getCondition()
   * @see #getStructuredControlStatement()
   * @generated
   */
  EReference getStructuredControlStatement_Condition();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.LoopStatement <em>Loop Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Statement</em>'.
   * @see org.mzattera.dsl.l101.LoopStatement
   * @generated
   */
  EClass getLoopStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.LoopStatement#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see org.mzattera.dsl.l101.LoopStatement#getBody()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Body();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.StoreStatement <em>Store Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Store Statement</em>'.
   * @see org.mzattera.dsl.l101.StoreStatement
   * @generated
   */
  EClass getStoreStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.StoreStatement#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Param</em>'.
   * @see org.mzattera.dsl.l101.StoreStatement#getParam()
   * @see #getStoreStatement()
   * @generated
   */
  EReference getStoreStatement_Param();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.StoreStatement#getStore <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Store</em>'.
   * @see org.mzattera.dsl.l101.StoreStatement#getStore()
   * @see #getStoreStatement()
   * @generated
   */
  EReference getStoreStatement_Store();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.PrintStatement <em>Print Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Statement</em>'.
   * @see org.mzattera.dsl.l101.PrintStatement
   * @generated
   */
  EClass getPrintStatement();

  /**
   * Returns the meta object for the containment reference list '{@link org.mzattera.dsl.l101.PrintStatement#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see org.mzattera.dsl.l101.PrintStatement#getParams()
   * @see #getPrintStatement()
   * @generated
   */
  EReference getPrintStatement_Params();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.PrintParameter <em>Print Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print Parameter</em>'.
   * @see org.mzattera.dsl.l101.PrintParameter
   * @generated
   */
  EClass getPrintParameter();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.NewLine <em>New Line</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>New Line</em>'.
   * @see org.mzattera.dsl.l101.NewLine
   * @generated
   */
  EClass getNewLine();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.GotoStatement <em>Goto Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto Statement</em>'.
   * @see org.mzattera.dsl.l101.GotoStatement
   * @generated
   */
  EClass getGotoStatement();

  /**
   * Returns the meta object for the reference '{@link org.mzattera.dsl.l101.GotoStatement#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Label</em>'.
   * @see org.mzattera.dsl.l101.GotoStatement#getLabel()
   * @see #getGotoStatement()
   * @generated
   */
  EReference getGotoStatement_Label();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.ContinueStatement <em>Continue Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Continue Statement</em>'.
   * @see org.mzattera.dsl.l101.ContinueStatement
   * @generated
   */
  EClass getContinueStatement();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.BreakStatement <em>Break Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Break Statement</em>'.
   * @see org.mzattera.dsl.l101.BreakStatement
   * @generated
   */
  EClass getBreakStatement();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.IfStatement <em>If Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If Statement</em>'.
   * @see org.mzattera.dsl.l101.IfStatement
   * @generated
   */
  EClass getIfStatement();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.IfStatement#getCode <em>Code</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Code</em>'.
   * @see org.mzattera.dsl.l101.IfStatement#getCode()
   * @see #getIfStatement()
   * @generated
   */
  EAttribute getIfStatement_Code();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.IfStatement#getThenClause <em>Then Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Then Clause</em>'.
   * @see org.mzattera.dsl.l101.IfStatement#getThenClause()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_ThenClause();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.IfStatement#getElseClause <em>Else Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Else Clause</em>'.
   * @see org.mzattera.dsl.l101.IfStatement#getElseClause()
   * @see #getIfStatement()
   * @generated
   */
  EReference getIfStatement_ElseClause();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.UntilStatement <em>Until Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Until Statement</em>'.
   * @see org.mzattera.dsl.l101.UntilStatement
   * @generated
   */
  EClass getUntilStatement();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.ForStatement <em>For Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Statement</em>'.
   * @see org.mzattera.dsl.l101.ForStatement
   * @generated
   */
  EClass getForStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.ForStatement#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see org.mzattera.dsl.l101.ForStatement#getInit()
   * @see #getForStatement()
   * @generated
   */
  EReference getForStatement_Init();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.ForStatement#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>End</em>'.
   * @see org.mzattera.dsl.l101.ForStatement#getEnd()
   * @see #getForStatement()
   * @generated
   */
  EReference getForStatement_End();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.WhileStatement <em>While Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While Statement</em>'.
   * @see org.mzattera.dsl.l101.WhileStatement
   * @generated
   */
  EClass getWhileStatement();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.VariableAccess <em>Variable Access</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Access</em>'.
   * @see org.mzattera.dsl.l101.VariableAccess
   * @generated
   */
  EClass getVariableAccess();

  /**
   * Returns the meta object for the reference '{@link org.mzattera.dsl.l101.VariableAccess#getStore <em>Store</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Store</em>'.
   * @see org.mzattera.dsl.l101.VariableAccess#getStore()
   * @see #getVariableAccess()
   * @generated
   */
  EReference getVariableAccess_Store();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.AdditiveOperator <em>Additive Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Additive Operator</em>'.
   * @see org.mzattera.dsl.l101.AdditiveOperator
   * @generated
   */
  EClass getAdditiveOperator();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.AdditiveOperator#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.mzattera.dsl.l101.AdditiveOperator#getLeft()
   * @see #getAdditiveOperator()
   * @generated
   */
  EReference getAdditiveOperator_Left();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.AdditiveOperator#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.mzattera.dsl.l101.AdditiveOperator#getOp()
   * @see #getAdditiveOperator()
   * @generated
   */
  EAttribute getAdditiveOperator_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.AdditiveOperator#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.mzattera.dsl.l101.AdditiveOperator#getRight()
   * @see #getAdditiveOperator()
   * @generated
   */
  EReference getAdditiveOperator_Right();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.MultiplicativeOperator <em>Multiplicative Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplicative Operator</em>'.
   * @see org.mzattera.dsl.l101.MultiplicativeOperator
   * @generated
   */
  EClass getMultiplicativeOperator();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.MultiplicativeOperator#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.mzattera.dsl.l101.MultiplicativeOperator#getLeft()
   * @see #getMultiplicativeOperator()
   * @generated
   */
  EReference getMultiplicativeOperator_Left();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.MultiplicativeOperator#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.mzattera.dsl.l101.MultiplicativeOperator#getOp()
   * @see #getMultiplicativeOperator()
   * @generated
   */
  EAttribute getMultiplicativeOperator_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.MultiplicativeOperator#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.mzattera.dsl.l101.MultiplicativeOperator#getRight()
   * @see #getMultiplicativeOperator()
   * @generated
   */
  EReference getMultiplicativeOperator_Right();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.UnaryOperator <em>Unary Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Operator</em>'.
   * @see org.mzattera.dsl.l101.UnaryOperator
   * @generated
   */
  EClass getUnaryOperator();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.UnaryOperator#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.mzattera.dsl.l101.UnaryOperator#getOp()
   * @see #getUnaryOperator()
   * @generated
   */
  EAttribute getUnaryOperator_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.mzattera.dsl.l101.UnaryOperator#getOperand <em>Operand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operand</em>'.
   * @see org.mzattera.dsl.l101.UnaryOperator#getOperand()
   * @see #getUnaryOperator()
   * @generated
   */
  EReference getUnaryOperator_Operand();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Current <em>Current</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Current</em>'.
   * @see org.mzattera.dsl.l101.Current
   * @generated
   */
  EClass getCurrent();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.mzattera.dsl.l101.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for class '{@link org.mzattera.dsl.l101.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see org.mzattera.dsl.l101.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.Constant#isNegative <em>Negative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Negative</em>'.
   * @see org.mzattera.dsl.l101.Constant#isNegative()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Negative();

  /**
   * Returns the meta object for the attribute '{@link org.mzattera.dsl.l101.Constant#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.mzattera.dsl.l101.Constant#getValue()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  L101Factory getL101Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.ProgramImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Var Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__VAR_DECLARATIONS = eINSTANCE.getProgram_VarDeclarations();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__BODY = eINSTANCE.getProgram_Body();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.VariableDeclarationImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Short</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__SHORT = eINSTANCE.getVariableDeclaration_Short();

    /**
     * The meta object literal for the '<em><b>Vars</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECLARATION__VARS = eINSTANCE.getVariableDeclaration_Vars();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.VariableImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '<em><b>Reg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__REG = eINSTANCE.getVariable_Reg();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.ExpressionImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.AssignmentStatementImpl <em>Assignment Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.AssignmentStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getAssignmentStatement()
     * @generated
     */
    EClass ASSIGNMENT_STATEMENT = eINSTANCE.getAssignmentStatement();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGNMENT_STATEMENT__OP = eINSTANCE.getAssignmentStatement_Op();

    /**
     * The meta object literal for the '<em><b>Operand</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT_STATEMENT__OPERAND = eINSTANCE.getAssignmentStatement_Operand();

    /**
     * The meta object literal for the '<em><b>Store</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGNMENT_STATEMENT__STORE = eINSTANCE.getAssignmentStatement_Store();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.StatementsImpl <em>Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.StatementsImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStatements()
     * @generated
     */
    EClass STATEMENTS = eINSTANCE.getStatements();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENTS__STATEMENTS = eINSTANCE.getStatements_Statements();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.StatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.LabelImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__NAME = eINSTANCE.getLabel_Name();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL__TARGET = eINSTANCE.getLabel_Target();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.SimpleStatementImpl <em>Simple Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.SimpleStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getSimpleStatement()
     * @generated
     */
    EClass SIMPLE_STATEMENT = eINSTANCE.getSimpleStatement();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.SimpleControlStatementImpl <em>Simple Control Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.SimpleControlStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getSimpleControlStatement()
     * @generated
     */
    EClass SIMPLE_CONTROL_STATEMENT = eINSTANCE.getSimpleControlStatement();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_CONTROL_STATEMENT__CODE = eINSTANCE.getSimpleControlStatement_Code();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.StructuredControlStatementImpl <em>Structured Control Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.StructuredControlStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStructuredControlStatement()
     * @generated
     */
    EClass STRUCTURED_CONTROL_STATEMENT = eINSTANCE.getStructuredControlStatement();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRUCTURED_CONTROL_STATEMENT__CONDITION = eINSTANCE.getStructuredControlStatement_Condition();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.LoopStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getLoopStatement()
     * @generated
     */
    EClass LOOP_STATEMENT = eINSTANCE.getLoopStatement();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__BODY = eINSTANCE.getLoopStatement_Body();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.StoreStatementImpl <em>Store Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.StoreStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getStoreStatement()
     * @generated
     */
    EClass STORE_STATEMENT = eINSTANCE.getStoreStatement();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE_STATEMENT__PARAM = eINSTANCE.getStoreStatement_Param();

    /**
     * The meta object literal for the '<em><b>Store</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STORE_STATEMENT__STORE = eINSTANCE.getStoreStatement_Store();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.PrintStatementImpl <em>Print Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.PrintStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getPrintStatement()
     * @generated
     */
    EClass PRINT_STATEMENT = eINSTANCE.getPrintStatement();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT_STATEMENT__PARAMS = eINSTANCE.getPrintStatement_Params();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.PrintParameterImpl <em>Print Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.PrintParameterImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getPrintParameter()
     * @generated
     */
    EClass PRINT_PARAMETER = eINSTANCE.getPrintParameter();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.NewLineImpl <em>New Line</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.NewLineImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getNewLine()
     * @generated
     */
    EClass NEW_LINE = eINSTANCE.getNewLine();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.GotoStatementImpl <em>Goto Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.GotoStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getGotoStatement()
     * @generated
     */
    EClass GOTO_STATEMENT = eINSTANCE.getGotoStatement();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOTO_STATEMENT__LABEL = eINSTANCE.getGotoStatement_Label();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.ContinueStatementImpl <em>Continue Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.ContinueStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getContinueStatement()
     * @generated
     */
    EClass CONTINUE_STATEMENT = eINSTANCE.getContinueStatement();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.BreakStatementImpl <em>Break Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.BreakStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getBreakStatement()
     * @generated
     */
    EClass BREAK_STATEMENT = eINSTANCE.getBreakStatement();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.IfStatementImpl <em>If Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.IfStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getIfStatement()
     * @generated
     */
    EClass IF_STATEMENT = eINSTANCE.getIfStatement();

    /**
     * The meta object literal for the '<em><b>Code</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IF_STATEMENT__CODE = eINSTANCE.getIfStatement_Code();

    /**
     * The meta object literal for the '<em><b>Then Clause</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__THEN_CLAUSE = eINSTANCE.getIfStatement_ThenClause();

    /**
     * The meta object literal for the '<em><b>Else Clause</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_STATEMENT__ELSE_CLAUSE = eINSTANCE.getIfStatement_ElseClause();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.UntilStatementImpl <em>Until Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.UntilStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getUntilStatement()
     * @generated
     */
    EClass UNTIL_STATEMENT = eINSTANCE.getUntilStatement();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.ForStatementImpl <em>For Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.ForStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getForStatement()
     * @generated
     */
    EClass FOR_STATEMENT = eINSTANCE.getForStatement();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STATEMENT__INIT = eINSTANCE.getForStatement_Init();

    /**
     * The meta object literal for the '<em><b>End</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_STATEMENT__END = eINSTANCE.getForStatement_End();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.WhileStatementImpl <em>While Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.WhileStatementImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getWhileStatement()
     * @generated
     */
    EClass WHILE_STATEMENT = eINSTANCE.getWhileStatement();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.VariableAccessImpl <em>Variable Access</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.VariableAccessImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getVariableAccess()
     * @generated
     */
    EClass VARIABLE_ACCESS = eINSTANCE.getVariableAccess();

    /**
     * The meta object literal for the '<em><b>Store</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_ACCESS__STORE = eINSTANCE.getVariableAccess_Store();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.AdditiveOperatorImpl <em>Additive Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.AdditiveOperatorImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getAdditiveOperator()
     * @generated
     */
    EClass ADDITIVE_OPERATOR = eINSTANCE.getAdditiveOperator();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITIVE_OPERATOR__LEFT = eINSTANCE.getAdditiveOperator_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITIVE_OPERATOR__OP = eINSTANCE.getAdditiveOperator_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITIVE_OPERATOR__RIGHT = eINSTANCE.getAdditiveOperator_Right();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.MultiplicativeOperatorImpl <em>Multiplicative Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.MultiplicativeOperatorImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getMultiplicativeOperator()
     * @generated
     */
    EClass MULTIPLICATIVE_OPERATOR = eINSTANCE.getMultiplicativeOperator();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATIVE_OPERATOR__LEFT = eINSTANCE.getMultiplicativeOperator_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATIVE_OPERATOR__OP = eINSTANCE.getMultiplicativeOperator_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATIVE_OPERATOR__RIGHT = eINSTANCE.getMultiplicativeOperator_Right();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.UnaryOperatorImpl <em>Unary Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.UnaryOperatorImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getUnaryOperator()
     * @generated
     */
    EClass UNARY_OPERATOR = eINSTANCE.getUnaryOperator();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNARY_OPERATOR__OP = eINSTANCE.getUnaryOperator_Op();

    /**
     * The meta object literal for the '<em><b>Operand</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_OPERATOR__OPERAND = eINSTANCE.getUnaryOperator_Operand();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.CurrentImpl <em>Current</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.CurrentImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getCurrent()
     * @generated
     */
    EClass CURRENT = eINSTANCE.getCurrent();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.InputImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '{@link org.mzattera.dsl.l101.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.mzattera.dsl.l101.impl.ConstantImpl
     * @see org.mzattera.dsl.l101.impl.L101PackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Negative</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__NEGATIVE = eINSTANCE.getConstant_Negative();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__VALUE = eINSTANCE.getConstant_Value();

  }

} //L101Package
