/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Print Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mzattera.dsl.l101.L101Package#getPrintParameter()
 * @model
 * @generated
 */
public interface PrintParameter extends EObject
{
} // PrintParameter
