/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.Program#getVarDeclarations <em>Var Declarations</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.Program#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Var Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.mzattera.dsl.l101.VariableDeclaration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Declarations</em>' containment reference list.
   * @see org.mzattera.dsl.l101.L101Package#getProgram_VarDeclarations()
   * @model containment="true"
   * @generated
   */
  EList<VariableDeclaration> getVarDeclarations();

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Statements)
   * @see org.mzattera.dsl.l101.L101Package#getProgram_Body()
   * @model containment="true"
   * @generated
   */
  Statements getBody();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.Program#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Statements value);

} // Program
