/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Store Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.StoreStatement#getParam <em>Param</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.StoreStatement#getStore <em>Store</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getStoreStatement()
 * @model
 * @generated
 */
public interface StoreStatement extends SimpleStatement
{
  /**
   * Returns the value of the '<em><b>Param</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param</em>' containment reference.
   * @see #setParam(Expression)
   * @see org.mzattera.dsl.l101.L101Package#getStoreStatement_Param()
   * @model containment="true"
   * @generated
   */
  Expression getParam();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.StoreStatement#getParam <em>Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Param</em>' containment reference.
   * @see #getParam()
   * @generated
   */
  void setParam(Expression value);

  /**
   * Returns the value of the '<em><b>Store</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Store</em>' containment reference.
   * @see #setStore(Expression)
   * @see org.mzattera.dsl.l101.L101Package#getStoreStatement_Store()
   * @model containment="true"
   * @generated
   */
  Expression getStore();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.StoreStatement#getStore <em>Store</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Store</em>' containment reference.
   * @see #getStore()
   * @generated
   */
  void setStore(Expression value);

} // StoreStatement
