/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Structured Control Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.StructuredControlStatement#getCondition <em>Condition</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getStructuredControlStatement()
 * @model
 * @generated
 */
public interface StructuredControlStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' containment reference.
   * @see #setCondition(AssignmentStatement)
   * @see org.mzattera.dsl.l101.L101Package#getStructuredControlStatement_Condition()
   * @model containment="true"
   * @generated
   */
  AssignmentStatement getCondition();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.StructuredControlStatement#getCondition <em>Condition</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' containment reference.
   * @see #getCondition()
   * @generated
   */
  void setCondition(AssignmentStatement value);

} // StructuredControlStatement
