/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.VariableDeclaration#isShort <em>Short</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.VariableDeclaration#getVars <em>Vars</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getVariableDeclaration()
 * @model
 * @generated
 */
public interface VariableDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Short</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Short</em>' attribute.
   * @see #setShort(boolean)
   * @see org.mzattera.dsl.l101.L101Package#getVariableDeclaration_Short()
   * @model
   * @generated
   */
  boolean isShort();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.VariableDeclaration#isShort <em>Short</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Short</em>' attribute.
   * @see #isShort()
   * @generated
   */
  void setShort(boolean value);

  /**
   * Returns the value of the '<em><b>Vars</b></em>' containment reference list.
   * The list contents are of type {@link org.mzattera.dsl.l101.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars</em>' containment reference list.
   * @see org.mzattera.dsl.l101.L101Package#getVariableDeclaration_Vars()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getVars();

} // VariableDeclaration
