/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.Variable#getName <em>Name</em>}</li>
 *   <li>{@link org.mzattera.dsl.l101.Variable#getReg <em>Reg</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getVariable()
 * @model
 * @generated
 */
public interface Variable extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.mzattera.dsl.l101.L101Package#getVariable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.Variable#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reg</em>' attribute.
   * @see #setReg(String)
   * @see org.mzattera.dsl.l101.L101Package#getVariable_Reg()
   * @model
   * @generated
   */
  String getReg();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.Variable#getReg <em>Reg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reg</em>' attribute.
   * @see #getReg()
   * @generated
   */
  void setReg(String value);

} // Variable
