/**
 * generated by Xtext 2.40.0
 */
package org.mzattera.dsl.l101;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Access</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mzattera.dsl.l101.VariableAccess#getStore <em>Store</em>}</li>
 * </ul>
 *
 * @see org.mzattera.dsl.l101.L101Package#getVariableAccess()
 * @model
 * @generated
 */
public interface VariableAccess extends Expression
{
  /**
   * Returns the value of the '<em><b>Store</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Store</em>' reference.
   * @see #setStore(Variable)
   * @see org.mzattera.dsl.l101.L101Package#getVariableAccess_Store()
   * @model
   * @generated
   */
  Variable getStore();

  /**
   * Sets the value of the '{@link org.mzattera.dsl.l101.VariableAccess#getStore <em>Store</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Store</em>' reference.
   * @see #getStore()
   * @generated
   */
  void setStore(Variable value);

} // VariableAccess
